name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies with UV
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        uv sync
    - name: Test with pytest
      run: |
        pytest tests
